### ISSUE TITLE
Add VTAPP Events as in Gallery

### ISSUE THREAD

**Issue by AlexJMercer** [SEDS-Aurora/Seds#21]
### Tasks to be completed

- [ ] Add all **5 VTAPP Events** in Gallery in the same format as previous event cards.

- [ ] Reverse the current order of events (Latest event should be shown at the top of the page)

- [ ] Add appropriate images in the "View More" section (Please get images from Documentation Team, or whoever has images of the events)
